name = "hex"
compatibility_date = "2026-08-07"

[[d1_databases]]
binding = "DB"
database_name = "hex"
database_id = "8902b21c-6616-472d-bac8-5df9248961ca"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "hex-assets"

[vars]
ADMIN_AUD = ""