/// <reference path="../.astro/types.d.ts" />
/// <reference path="../worker-configuration.d.ts" />

// `cloudflare:workers` is a virtual module provided by the Workers runtime at
// runtime; no package ships type declarations for it, so declare it here.
// `Env` (DB, BUCKET) is the global generated by `wrangler types`.
declare module 'cloudflare:workers' {
  export const env: Env;
}
